[package]
name = "poker"
version = "0.1.0"
edition = "2024"

[lib]
name = "poker"
path = "lib.rs"

[dependencies]
num-derive = "0.4.2"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.2"
